# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa300944e4a38defe81b4852958994ae59cacc39f6e772c76d6936b198dfdf5f6ef04f5a7fefc21bd2b41107921342bf2e0d60246ff6ad31aa210697635300a2

test:
  secret_key_base: 99089a58367a7815bc05368aec52273dc432bb54b75480e2eea48f9538a65363e4c0dc0830594a12f6c3de72d618c5065773d1afc456e0adb86a7f42f6353b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
